### ISSUE TITLE
Acsess denied

### ISSUE THREAD

**Issue by Adadeane** [Kieran-Lock/AutoKahoot#1]
I get error fatal: could not create work tree dir 'AutoKahoot': Permission denied when i use the command

**Comment by Kieran-Lock** [comment]
I will presume you are referring to the git clone command provided in the project README. If so, make sure you have write access (i.e. can create files) in the directory you are cloning in.

If you have admin perms, consider using `chown` to change the ownership of the folder.
If not, perhaps another process is running, and blocking any write access to this folder?

For reference: https://stackoverflow.com/questions/20276895/could-not-create-work-tree-dir-example-com-permission-denied
