### ISSUE TITLE
Cant be used.

### ISSUE THREAD

**Issue by TheBjdjlCraft** [Kieran-Lock/AutoKahoot#3]
After running `git clone https://github.com/Kieran-Lock/AutoKahoot.git` and then running the command `python3 main.py` i am hit with error code 

> python3: can't open file 'C:\\Users\\GrensingJulian5I\\main.py': [Errno 2] No such file or directory

**Comment by Kieran-Lock** [comment]
Looks like either the clone failed (in which case retry) or you're not in the right directory to run the script. Try `cd C:\Users\GrensingJulian5I\AutoKahoot` before running `python3 main.py`, which should put you in the right folder, assuming the clone did work.
